[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "daily_ai"
version = "0.0.1"
description = "Orchestrator for AI bots with Daily"
dependencies = [
    "daily-python",
    "Pillow",
    "typing-extensions",
    "openai",
    "google-cloud-texttospeech",
    "azure-cognitiveservices-speech",
    "pyht",
    "opentelemetry-sdk",
    "aiohttp",
    "fal"
]

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["src"]
